name: Typecheck

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[typecheck,test]'
      - run: echo "::add-matcher::./.github/problem_matchers/mypy.jsonc"
      - run: mypy ./hypothesis_torch_utils
      - run: echo "::remove-matcher owner=mypy::"

  pyright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[typecheck,test]'
      - run: echo "::add-matcher::./.github/problem_matchers/pyright.jsonc"
      - run: pyright ./hypothesis_torch_utils
      - run: echo "::remove-matcher owner=pyright::"
      - run: pyright --verifytypes hypothesis_torch_utils --ignoreexternal --pythonversion 3.10 --pythonplatform Linux --verbose
